### ISSUE TITLE
[Feature Request] Recursive Suspend/Resume

### ISSUE THREAD

**Issue by MauricePasternak** [FedericoCarboni/node-ntsuspend#5]
This is an excellent library which addresses a shortcoming of vanilla NodeJS. It would be beneficial if an option could be added in where the suspend/resume functions apply to children/grandchildren of a spawned process.

A common scenario this would greatly assist in is controlling executables that were lauched with `spawn`.

**Comment by federicocarboni** [comment]
I don't know of any Windows kernel function that does that. If you manage to get a list of the PIDs of the children processes you could just loop through that and `suspend` each process one by one. You could get the process tree from tasklist or pslist and then traverse it to get the PID of all the processes you want to suspend.

I think gathering this kind of process information is a bit out of the scope of this library since Windows doesn't provide it in an accessible manner (for example process info in Linux is easily accessible under `/proc`).

Did you find any programs that weren't suspended correctly because of their children processes? If so, having a concrete example may help.

**Comment by MauricePasternak** [comment]
As per your suggestion, I have found that the `wmic` command on Windows is able to give STDOUT data which lists the childprocesses. Just a matter of capturing with regex and repeating things recursively after that. Example I use is as follows:

```
/**
 * Retrieve an array of process IDs in a Windows setting.
 * @param startingPid The PID from which to retrieve the PIDs of all descendants.
 * @returns An array of PIDs, the order of which follows child1 > grandchild1_1 ; child2 > grandchild2_1, grandchild2_2, etc.
 */
export function getWindowsPIDS(startingPid: number) {
  if (process.platform !== "win32") {
    throw new Error("This function must only be executed on a Windows platform.");
  }

  // Instantiate the PIDs array which will be referenced in the recursive function
  const pids: number[] = [];

  /**
   * Adds the process ids of child processes to the outer-scope pids array.
   * @param parentPid The process ID of a parent process.
   */
  function getChildPids(parentPid: number) {
    const { stdout } = spawn.sync("wmic", ["process", "where", `(ParentProcessId=${parentPid})`, "get", "ProcessId"], {
      encoding: "ascii",
    });

    if (/\d+/gm.test(stdout)) {
      const childPids = stdout.match(/\d+/gm).map(pid => parseInt(pid));
      for (const childPid of childPids) {
        pids.push(childPid);
        getChildPids(childPid);
      }
    }
  }
  getChildPids(startingPid);
  return pids;
}
```

I opted for a flat array approach instead of a nested object. From here, a user may loop over the array of PIDs and suspend/resume as their project requires.

EDIT: For clarity, I use the `cross-spawn` library over NodeJS's version, due to its more robust behavior.
